/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

 import java.sql.Connection;
 import java.sql.ResultSet;
 import java.sql.SQLException;
 import java.sql.Statement;
 
 import javax.swing.JOptionPane;
 
 /**
  *
  * @author G15
  */
 public class Add_Subject extends javax.swing.JFrame {
 
     /**
      * Creates new form Add_Subject
      */
     public Add_Subject() {
         initComponents();
         setLocationRelativeTo(null);
     }
 
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
 
         jComboBox1 = new javax.swing.JComboBox<>();
         jPanel1 = new javax.swing.JPanel();
         jPanel2 = new javax.swing.JPanel();
         jLabel_Subject_ID = new javax.swing.JLabel();
         jTextField1 = new javax.swing.JTextField();
         jButton_Submit = new javax.swing.JButton();
         jLabel_Add_Subject = new javax.swing.JLabel();
         jButton_Back = new javax.swing.JButton();
 
         jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
 
         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         setResizable(false);
 
         jPanel1.setBackground(new java.awt.Color(12, 137, 112));
 
         jPanel2.setBackground(new java.awt.Color(255, 255, 255));
 
         jLabel_Subject_ID.setText("SUBJECT ID :");
 
         jTextField1.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField1ActionPerformed(evt);
             }
         });
 
         jButton_Submit.setText("SUBMIT");
 
         jButton_Submit.addActionListener(new java.awt.event.ActionListener(){
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButtonSubmit1ActionPerformed(evt);
             }
         });
         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
         jPanel2.setLayout(jPanel2Layout);
         jPanel2Layout.setHorizontalGroup(
             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel2Layout.createSequentialGroup()
                 .addGap(82, 82, 82)
                 .addComponent(jLabel_Subject_ID)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jButton_Submit)
                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addContainerGap(43, Short.MAX_VALUE))
         );
         jPanel2Layout.setVerticalGroup(
             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel2Layout.createSequentialGroup()
                 .addGap(54, 54, 54)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel_Subject_ID)
                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(27, 27, 27)
                 .addComponent(jButton_Submit)
                 .addContainerGap(114, Short.MAX_VALUE))
         );
 
         jLabel_Add_Subject.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
         jLabel_Add_Subject.setForeground(new java.awt.Color(255, 255, 255));
         jLabel_Add_Subject.setText("Add_Subject");
 
         jButton_Back.setText("BACK");
         jButton_Back.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton_BackActionPerformed(evt);
             }
         });
 
         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
         jPanel1.setLayout(jPanel1Layout);
         jPanel1Layout.setHorizontalGroup(
             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addComponent(jButton_Back)
                 .addGap(62, 62, 62)
                 .addComponent(jLabel_Add_Subject)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
         jPanel1Layout.setVerticalGroup(
             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addContainerGap()
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel_Add_Subject)
                     .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap(18, Short.MAX_VALUE))
         );
 
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
         getContentPane().setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         );
 
         pack();
     }// </editor-fold>//GEN-END:initComponents
 
     private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
         // TODO add your handling code here:
     }//GEN-LAST:event_jTextField1ActionPerformed
 
     private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
         this.dispose();
     }//GEN-LAST:event_jButton_BackActionPerformed
 
     private void jButtonSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
 
     
         Connection connection = SQLConnection.getConnection2();
         try {
                 Statement statement = connection.createStatement();
                 if (hasRegistered(jTextField1.getText())) {
                     JOptionPane.showMessageDialog(this, "You have already registered this subject", "Error", JOptionPane.ERROR_MESSAGE);
                     return;
                 }
                 if(!subjectExists(jTextField1.getText())){
                     JOptionPane.showMessageDialog(this, "Wrong subject_id please try again", "Error", JOptionPane.ERROR_MESSAGE);
                     return;
                 }
                     String sql = String.format("INSERT INTO registration (std_id,subject_id,grade)\r\n" + //
                                                 "Values (\"%S\",\"%S\",null)",LoginStd.std_id,jTextField1.getText());
                     statement.executeUpdate(sql);
                     JOptionPane.showMessageDialog(this,"Register subject success","Success", JOptionPane.INFORMATION_MESSAGE);
                 
                 
         } catch (SQLException e) {
             // TODO Auto-generated catch block
             e.printStackTrace();
         }
     }
     //GEN-LAST:event_jTextField1ActionPerformed
     public boolean hasRegistered(String text){
         Connection connection = SQLConnection.getConnection2();
         try {
             Statement statement = connection.createStatement();
             String sql = String.format("SELECT all_subjects.subject_id,registration.std_id\r\n" + //
                                 "FROM all_subjects JOIN registration \r\n" + //
                                 "ON registration.subject_id = all_subjects.subject_id\r\n" + //
                                 "WHERE registration.std_id = \"%S\"",LoginStd.std_id);
             ResultSet resultSet = statement.executeQuery(sql);
             while (resultSet.next()) {
                 if (text.equals(resultSet.getString("subject_id"))) {
                     return true;
                 }
             }
             
         } catch (SQLException e) {
             e.printStackTrace();
         }
         return false;    
     }
 
     public boolean subjectExists(String text){
         try {
             Connection connection = SQLConnection.getConnection2();
             Statement statement = connection.createStatement();
             String sql= String.format("SELECT subject_id FROM all_subjects WHERE subject_id = " + text);
             ResultSet rs = statement.executeQuery(sql);
             if (!rs.next())
                return false;
             return true;
         } catch (SQLException e) {
             // TODO Auto-generated catch block
             e.printStackTrace();
             return true;
         }
     }
 
     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
         /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
          */
         try {
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
                     break;
                 }
             }
         } catch (ClassNotFoundException ex) {
             java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
             java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
             java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(Add_Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
         //</editor-fold>
 
         /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 new Add_Subject().setVisible(true);
             }
         });
     }
 
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton_Back;
     private javax.swing.JButton jButton_Submit;
     private javax.swing.JComboBox<String> jComboBox1;
     private javax.swing.JLabel jLabel_Add_Subject;
     private javax.swing.JLabel jLabel_Subject_ID;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JTextField jTextField1;
     // End of variables declaration//GEN-END:variables
 }
 
