/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author G15
 */
public class AddHomeWork extends javax.swing.JFrame {

    static Connection connection;

    /**
     * Creates new form AddHomeWork
     */
    public AddHomeWork() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        // this.teacher_id = teacher_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackHW = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LabelStudent_ID = new javax.swing.JLabel();
        LabelSubject_ID = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelDue = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jTextST_ID = new javax.swing.JTextField();
        jTextSJ_ID = new javax.swing.JTextField();
        jTextDC = new javax.swing.JTextField();
        jTextDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(12, 137, 112));

        BackHW.setBackground(new java.awt.Color(0, 102, 102));
        BackHW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackHW.setForeground(new java.awt.Color(255, 255, 255));
        BackHW.setText("BACK");
        BackHW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackHW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackHW, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackHW)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(12, 137, 112));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        LabelStudent_ID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelStudent_ID.setText(" STUDENT ID :");

        LabelSubject_ID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelSubject_ID.setText("SUBJECT ID :");

        jLabelDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDescription.setText("DESCRIPTION :");

        jLabelDue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDue.setText("DUE :");

        jButtonSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSubmit.addActionListener(e -> {
            LocalDate assignedDate = LocalDate.now();
            String dueDate = jTextDate.getText();
            String subjectID = jTextSJ_ID.getText();
            String description = jTextDC.getText();
            String assignedToStd = jTextST_ID.getText();
            String assignedByTeacher = Login.teacherId;
            try{
                connection = SQLConnection.getConnection1();
                Statement statement = connection.createStatement();

                if (!doesExist(assignedToStd)){
                    JOptionPane.showMessageDialog(this, "Unknown student ID", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!hasRegistered(assignedToStd, subjectID)){
                    String msg = String.format("%s hasn't registered %s", assignedToStd, subjectID);
                    JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!doesTeach(subjectID)){
                    String msg = String.format("%s doesn't teach %s", Login.teacherId, subjectID);
                    JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String query = String.format("INSERT INTO homework (assigned_date, due_date, subject_id, description, assigned_to_std, assigned_by_teacher) VALUES (\"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\")", assignedDate, dueDate, subjectID, description, assignedToStd, assignedByTeacher);
                statement.executeUpdate(query);
                String msg = String.format("(%s) %s assigned %s to %s (due %s)", assignedDate, assignedByTeacher, subjectID,  assignedToStd, dueDate);
                JOptionPane.showMessageDialog(this, msg, "Success", JOptionPane.INFORMATION_MESSAGE);
            }catch (SQLException exept) {
                exept.printStackTrace();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSubject_ID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelStudent_ID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextSJ_ID)
                            .addComponent(jTextST_ID)
                            .addComponent(jTextDC, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabelDue)
                        .addGap(18, 18, 18)
                        .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelStudent_ID)
                    .addComponent(jTextST_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSubject_ID)
                    .addComponent(jTextSJ_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDue)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(176, 176, 176)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void BackHWActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Homework backHW = new Homework();
        backHW.setVisible(true);
        backHW.setLocationRelativeTo(null);
        backHW.pack();
        this.dispose();
    }   
    
    public boolean doesExist(String std_id) throws SQLException{
        Statement statement = connection.  createStatement();
        String fectchStdQuery = String.format("SELECT std_id FROM students WHERE std_id = \"%s\"", std_id);
        ResultSet rs = statement.executeQuery(fectchStdQuery);
        return rs.next();
    }

    public boolean hasRegistered(String std_id, String subject_id) throws SQLException {
        Statement statement = connection.  createStatement();
        String fectchStdQuery = String.format("SELECT std_id, subject_id FROM registration WHERE std_id = \"%s\" AND subject_id = \"%s\"", std_id, subject_id);
        ResultSet rs = statement.executeQuery(fectchStdQuery);
        return rs.next();
    }

    public boolean doesTeach(String subject_id) throws SQLException {
            Statement statement = connection.  createStatement();
            String fectchStdQuery = String.format("SELECT teacher_id, subject_id FROM teachers WHERE teacher_id = \"%s\" AND subject_id = \"%s\"", Login.teacherId, subject_id);
            ResultSet rs = statement.executeQuery(fectchStdQuery);
            return rs.next();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHomeWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHomeWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHomeWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHomeWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new AddHomeWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BackHW;
    private javax.swing.JLabel LabelStudent_ID;
    private javax.swing.JLabel LabelSubject_ID;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelDue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextDC;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextSJ_ID;
    private javax.swing.JTextField jTextST_ID;
    // End of variables declaration                   
}
