/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class LoginStd extends javax.swing.JFrame {
    /**
     * Creates new form LoginStd
     */
    public LoginStd() {
        initComponents();
        BG1();
        IconFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGPanel = new javax.swing.JPanel();
        BG1 = new javax.swing.JLabel();
        TITLEStd = new javax.swing.JLabel();
        LOGINTEXT = new javax.swing.JLabel();
        line1 = new javax.swing.JPanel();
        line2 = new javax.swing.JPanel();
        Directiontext = new javax.swing.JLabel();
        Fieldpassanduser = new javax.swing.JPanel();
        FieldUser = new javax.swing.JTextField();
        TextUser = new javax.swing.JLabel();
        Passwordfield = new javax.swing.JPasswordField();
        TextPass = new javax.swing.JLabel();
        LoginBT = new javax.swing.JButton();
        showbox = new javax.swing.JCheckBox();
        SwarptoTeacher = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BGPanel.setBackground(new java.awt.Color(12, 137, 112));
        BGPanel.setPreferredSize(new java.awt.Dimension(240, 435));

        TITLEStd.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TITLEStd.setForeground(new java.awt.Color(255, 255, 255));
        TITLEStd.setText("STUDENT");

        LOGINTEXT.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LOGINTEXT.setForeground(new java.awt.Color(255, 255, 255));
        LOGINTEXT.setText("LOGIN");

        line1.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        line2.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout line2Layout = new javax.swing.GroupLayout(line2);
        line2.setLayout(line2Layout);
        line2Layout.setHorizontalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        line2Layout.setVerticalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Directiontext.setForeground(new java.awt.Color(255, 255, 255));
        Directiontext.setText("Fill your information for login");

        Fieldpassanduser.setBackground(new java.awt.Color(234, 234, 234));

        FieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUserActionPerformed(evt);
            }
        });

        TextUser.setBackground(new java.awt.Color(0, 0, 0));
        TextUser.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        TextUser.setText("USERNAME");

        Passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordfieldActionPerformed(evt);
            }
        });

        TextPass.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        TextPass.setText("PASSWORD");

        LoginBT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginBT.setBorder(null);
        LoginBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBT.setLabel("LOGIN");
        LoginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTActionPerformed(evt);
            }
        });

        showbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showbox.setLabel("show");
        showbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FieldpassanduserLayout = new javax.swing.GroupLayout(Fieldpassanduser);
        Fieldpassanduser.setLayout(FieldpassanduserLayout);
        FieldpassanduserLayout.setHorizontalGroup(
            FieldpassanduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FieldpassanduserLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(FieldpassanduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showbox)
                    .addComponent(TextPass)
                    .addComponent(TextUser)
                    .addComponent(FieldUser, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(Passwordfield))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FieldpassanduserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginBT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        FieldpassanduserLayout.setVerticalGroup(
            FieldpassanduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FieldpassanduserLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TextUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(TextPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(showbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginBT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        SwarptoTeacher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SwarptoTeacher.setText("TEACHER");
        SwarptoTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SwarptoTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwarptoTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BGPanelLayout = new javax.swing.GroupLayout(BGPanel);
        BGPanel.setLayout(BGPanelLayout);
        BGPanelLayout.setHorizontalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addComponent(BG1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGPanelLayout.createSequentialGroup()
                        .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(line1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(SwarptoTeacher, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGPanelLayout.createSequentialGroup()
                                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TITLEStd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGPanelLayout.createSequentialGroup()
                                        .addComponent(LOGINTEXT)
                                        .addGap(22, 22, 22)))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGPanelLayout.createSequentialGroup()
                                .addComponent(Directiontext)
                                .addGap(44, 44, 44))))
                    .addComponent(Fieldpassanduser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        BGPanelLayout.setVerticalGroup(
            BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BGPanelLayout.createSequentialGroup()
                .addGroup(BGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGPanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel2))
                    .addGroup(BGPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(TITLEStd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LOGINTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(Directiontext)
                        .addGap(14, 14, 14)
                        .addComponent(Fieldpassanduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SwarptoTeacher)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Fill Username
    private void FieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUserActionPerformed
    //Fill Password
    private void PasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordfieldActionPerformed

    }//GEN-LAST:event_PasswordfieldActionPerformed
    //Show Password
    private void showboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showboxActionPerformed
        if (showbox.isSelected()) {
            Passwordfield.setEchoChar((char) 0);
        } else {
            Passwordfield.setEchoChar('*');
        }
    }//GEN-LAST:event_showboxActionPerformed
    //Swarp to Teacher
    private void SwarptoTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwarptoTeacherActionPerformed
        Login Teacher = new Login();
        Teacher.setVisible(true);
        Teacher.pack();
        Teacher.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SwarptoTeacherActionPerformed

    private void LoginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTActionPerformed
        String password = new String(Passwordfield.getPassword());
            if(checkAccount(FieldUser.getText(), password)){
            MenuStudent menustudent = new MenuStudent();
            menustudent.setVisible(true);
            menustudent.pack();
            menustudent.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_LoginBTActionPerformed
    //Icon Frame
    private void IconFrame(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("2118256.png")));
        
    }
    //BackGround JFrame
     public void BG1(){
        ImageIcon icon = new ImageIcon("src/pics/nontri-59_19.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(674, 590,Image.SCALE_SMOOTH);
        ImageIcon ScaleIcon = new ImageIcon(imgScale);
        BG1.setIcon(ScaleIcon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginStd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginStd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginStd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginStd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginStd().setVisible(true);
            }
        });
    }
    public boolean checkAccount(String id,String password){
        try{
            Connection connection = SQLConnection.getConnection1();
            Statement statement = connection.createStatement();
            String sql = String.format("SELECT std_id,std_password FROM students WHERE std_id=\"%s\" AND std_password=\"%s\"",id,password);

            ResultSet resultset = statement.executeQuery(sql);
            return resultset.next();
        }catch(Exception e){
            System.out.println(e);
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG1;
    private javax.swing.JPanel BGPanel;
    private javax.swing.JLabel Directiontext;
    private javax.swing.JTextField FieldUser;
    private javax.swing.JPanel Fieldpassanduser;
    private javax.swing.JLabel LOGINTEXT;
    private javax.swing.JButton LoginBT;
    private javax.swing.JPasswordField Passwordfield;
    private javax.swing.JButton SwarptoTeacher;
    private javax.swing.JLabel TITLEStd;
    private javax.swing.JLabel TextPass;
    private javax.swing.JLabel TextUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel line1;
    private javax.swing.JPanel line2;
    private javax.swing.JCheckBox showbox;
    // End of variables declaration//GEN-END:variables
}
